### ISSUE TITLE
No linux webdrivers?

### ISSUE THREAD

**Issue by mihxil** [npo-poms/functional-tests#108]
I'm trying to work out how I would fix that (we want to run it in a docker with linux)

**Comment by mihxil** [comment]
['https://github.com/fhoeben/hsac-fitnesse-fixtures/tree/main'
](https://github.com/fhoeben/hsac-fitnesse-fixtures/blob/main/src/assembly/standalone.xml)


'      
                <exclude>webdrivers/*-linux-*</exclude>'

wtf?

**Comment by mihxil** [comment]
I tried to fix it in https://github.com/npo-poms/hsac-fitnesse-fixtures/

This makes it work a bit further. But I encounter the next issue:

{code}
__EXCEPTION__:ABORT_SLIM_TEST:nl.hsac.fitnesse.fixture.slim.StopTestException: Could not start a new session. Response code 500. Message: Process unexpectedly closed with status 1
Host info: host: '449923e26681', ip: '172.17.0.2'
Build info: version: '4.16.1', revision: '9b4c83354e'
System info: os.name: 'Linux', os.arch: 'aarch64', os.version: '6.4.16-linuxkit', java.version: '11.0.21'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {profile: UEsDBBQACAgIABthOVgAAAAAAAA...}}]}]
at nl.hsac.fitnesse.fixture.util.selenium.driverfactory.DriverManager.getSeleniumHelper(DriverManager.java:52) [hsac-fitnesse-fixtures-5.3.8-SNAPSHOT.jar]
at nl.hsac.fitnesse.fixture.slim.web.SeleniumDriverSetup.setAndUseDriverFactory(SeleniumDriverSetup.java:288) [hsac-fitnesse-fixtures-5.3.8-SNAPSHOT.jar]
at nl.hsac.fitnesse.fixture.slim.web.SeleniumDriverSetup.startDriverForWithProfile(SeleniumDriverSetup.java:100) [hsac-fitnesse-fixtures-5.3.8-SNAPSHOT.jar]
at nl.hsac.fitnesse.fixture.slim.web.SeleniumDriverSetup.startDriverFor(SeleniumDriverSetup.java:105) [hsac-fitnesse-fixtures-5.3.8-SNAPSHOT.jar]
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [n/a]
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [n/a]
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [n/a]
at java.base/java.lang.reflect.Method.invoke(Method.java:566) [rt.jar]
{code}

**Comment by mihxil** [comment]
That might simply mean that there is not firefox. I installed somethign with apt-get, but that seems to be a bit more complicated then that.

**Comment by mihxil** [comment]
I figured that out. For now I just committed the drivers. I think it would be handier if hsac-fitnesse-fictures just contained them too.

**Comment by mihxil** [comment]
See https://github.com/fhoeben/hsac-fitnesse-fixtures/issues/600
